<a href="https://colab.research.google.com/github/ophelia-coder/-InClassActivity-112524-/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import tensorflow as tf

In [108]:
import numpy as np



In [109]:
a = np.random.randint(1,30,size=16)
print(a)


[ 3 26 19 21 17  7  2  8  5 10 24 13 24 15  3  5]


In [110]:
b = np.reshape(a,(4,4))
print(b)

[[ 3 26 19 21]
 [17  7  2  8]
 [ 5 10 24 13]
 [24 15  3  5]]


In [111]:
print(b[(0,1,2,3),(0,1,2,3)])

[ 3  7 24  5]


In [112]:
ans = []

for i in range(b.shape[0]):
  ans.append(int(b[i,i]))

ans = np.array(ans)
print(ans)

[ 3  7 24  5]


In [113]:
c = np.reshape(b,(-1))
print(c)

[ 3 26 19 21 17  7  2  8  5 10 24 13 24 15  3  5]


In [114]:
A = [4,35,5,6,7,2,6,3,5,7,82,4]
print(A)

[4, 35, 5, 6, 7, 2, 6, 3, 5, 7, 82, 4]


In [115]:
import scipy.stats as stats

a = stats.binom(p=0.5, n=10)

num = a.rvs(200)
# print(num)

num = np.array([
    [-13, -13,   4,   6,  13,  13,  -4,  10],
    [-10,   3,  11,  -1,   8,  -7, -10,  -9],
    [ -5,  11,  -5, -12,   6,  -4, -14,   3],
    [-12,   7,  -6,  12,  -6,   9,   1,  -5]
]
)
def count_digits(x):
  count = np.zeros(10, dtype=np.int16)
  print(count)

  # print(x)
  x = x.reshape(-1)

  for i in x:
    if i >=0 and i <=9:
      count[i] += 1

  return count

q5 = count_digits(num)
print(q5)

[0 0 0 0 0 0 0 0 0 0]
[0 1 0 2 1 0 2 1 1 1]


In [116]:
def sum_loop(A):
    s = 0
    for a in A.reshape(-1):
        s += a
    return s

In [117]:
x1 = np.array([1,2])
x2 = np.array([4,6])


def dot_prod(a,b):
  c = a*b
  c = sum_loop(c)
  return c

q7 = dot_prod(x1,x2)

print(q7)

16


In [118]:
def euc_dis(a,b):
  c = a - b
  c = c**2
  c = np.sum(c)
  c = np.sqrt(c)
  return c

q8 = euc_dis(x1,x2)
print(q8)

5.0


In [119]:
y = np.array([0,1,0,1])
p = np.array([1,1,0,0])

c = y == p

print(c)

print(np.sum(c))

acc = np.sum(c)/len(p)
print(acc)

[False  True  True False]
2
0.5


In [120]:
p = np.array([1.1,0.85,0.2])
y = np.array([0.9,0.7,0.1])

def mse(p,y):
  e = p-y
  se = e**2
  se = np.sum(se)
  mse = se/len(y)
  return mse

q11 = mse(p,y)

print(q11)

print(np.var(p ))

0.02416666666666668
0.14388888888888893


In [131]:
X = np.array([
    [6, 1, 2, 3, 3],
    [0, 6, 1, 4, 5],
    [9, 2, 6, 0, 5],
    [8, 2, 9, 3, 4],
    [3, 1, 7, 0, 2],
    [6, 2, 0, 4, 6],
    [9, 0, 0, 9, 8],
    [9, 6, 1, 8, 4],
    [0, 4, 1, 5, 5],
    [3, 4, 5, 5, 0]
])

def sel_feat(x,n):

  var = np.var(x,axis=0)
  print(var)

  sorted_x = np.sort(var)

  print(sorted_x)

  a = np.argsort(var)
  print(a)

  col = a[-n:]
  print(col)

  return x[:,col]

q12 = sel_feat(X,3)

print(q12)




[11.61  3.96  9.56  7.69  4.36]
[ 3.96  4.36  7.69  9.56 11.61]
[1 4 3 2 0]
[3 2 0]
[[3 2 6]
 [4 1 0]
 [0 6 9]
 [3 9 8]
 [0 7 3]
 [4 0 6]
 [9 0 9]
 [8 1 9]
 [5 1 0]
 [5 5 3]]


In [125]:
import numpy as np

X = np.array([
    [6, 1, 2, 3, 3],
    [0, 6, 1, 4, 5],
    [9, 2, 6, 0, 5],
    [8, 2, 9, 3, 4],
    [3, 1, 7, 0, 2],
    [6, 2, 0, 4, 6],
    [9, 0, 0, 9, 8],
    [9, 6, 1, 8, 4],
    [0, 4, 1, 5, 5],
    [3, 4, 5, 5, 0]
])

def sel_feat(x, n):
    # Variance of each column
    variances = np.var(x, axis=0)

    # Indices of top-n columns (largest variances)
    top_idx = np.argsort(variances)[-n:]

    # Return those columns from the original data
    return x[:, top_idx]

q12 = sel_feat(X, 2)
print(q12)


[[2 6]
 [1 0]
 [6 9]
 [9 8]
 [7 3]
 [0 6]
 [0 9]
 [1 9]
 [1 0]
 [5 3]]
